use std::path::PathBuf;
use tokio::fs;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelFileConfig {
    pub model_id: String,
    pub gguf_filename: String,
    pub model_dir: PathBuf,
}

/// Generate Ollama Modelfile - minimal format
pub fn generate_modelfile_content(config: &ModelFileConfig) -> String {
    format!(
        "# Generated by Solyn\n\
         # Hugging Face Model: {}\n\n\
         FROM ./{}",
        config.model_id, config.gguf_filename
    )
}

/// Always returns "Modelfile" - no quantization-specific naming
pub fn get_modelfile_name() -> String {
    "Modelfile".to_string()
}

pub async fn write_modelfile(
    model_dir: &PathBuf,
    config: &ModelFileConfig,
) -> Result<PathBuf, String> {
    let content = generate_modelfile_content(config);
    let filename = get_modelfile_name();
    let path = model_dir.join(filename);


    fs::write(&path, content)
        .await
        .map_err(|e| format!("Failed writing Modelfile: {}", e))?;

    Ok(path)
}

/// Generate metadata.json for the downloaded model
pub async fn write_metadata(
    model_dir: &PathBuf,
    model_id: &str,
    gguf_filename: &str,
    quantization: Option<String>,
    parameter_count: Option<String>,
) -> Result<PathBuf, String> {
    use std::collections::HashMap;

    let mut metadata = HashMap::new();
    metadata.insert("model_id".to_string(), model_id.to_string());
    metadata.insert("filename".to_string(), gguf_filename.to_string());
    
    if let Some(quant) = quantization {
        metadata.insert("quantization".to_string(), quant);
    }
    
    if let Some(params) = parameter_count {
        metadata.insert("parameter_count".to_string(), params);
    }

    let json_content = serde_json::to_string_pretty(&metadata)
        .map_err(|e| format!("Failed to serialize metadata: {}", e))?;

    let path = model_dir.join("metadata.json");

    fs::write(&path, json_content)
        .await
        .map_err(|e| format!("Failed writing metadata.json: {}", e))?;

    Ok(path)
}